FROM python:3.13-slim AS builder
WORKDIR /app
RUN apt-get update && apt-get upgrade && apt-get install -y build-essential && rm -rf /var/cache/apt/lists/*
COPY requirements.txt .
RUN pip install --user -r requirements.txt
COPY . .


FROM python:3.13-slim
WORKDIR /app
COPY --from=builder /app /app
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
EXPOSE 5000
CMD ["python", "app.py"]


